-- Platform donations (site_support) and RPC

create table if not exists public.platform_donations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  amount numeric not null check (amount > 0),
  created_at timestamptz not null default now()
);

alter table public.platform_donations enable row level security;

create policy "Users can read own platform donations"
  on public.platform_donations
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Service role full access platform donations"
  on public.platform_donations
  for all
  to service_role
  using (true)
  with check (true);

create or replace function public.donate_to_platform(p_amount numeric)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'Invalid amount';
  end if;

  insert into public.platform_donations (user_id, amount)
  values (auth.uid(), p_amount);
end;
$$;

grant execute on function public.donate_to_platform(numeric) to authenticated;
