-- Mascotas perdidas y encontradas (módulo 1)

create table public.lost_pets (
  id bigint generated by default as identity primary key,
  name text not null,
  breed text,
  color text,
  location text,
  date_text text,
  description text,
  reward text,
  contact text,
  status text not null default 'normal',
  reported_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.found_pets (
  id bigint generated by default as identity primary key,
  type text not null,
  breed text,
  color text,
  location text,
  date_text text,
  description text,
  condition text,
  contact text,
  match text,
  status text not null default 'normal',
  reported_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create index lost_pets_reported_by_idx on public.lost_pets (reported_by);
create index found_pets_reported_by_idx on public.found_pets (reported_by);
