-- Tercer módulo: precios y veterinarias (feature flag)

create table public.food_prices (
  id bigint generated by default as identity primary key,
  brand text not null,
  weight text,
  price numeric not null default 0,
  store text,
  available text,
  created_at timestamptz not null default now()
);

create table public.vets (
  id bigint generated by default as identity primary key,
  name text not null,
  services text,
  location text,
  phone text,
  hours text,
  promo text,
  owner_id uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create index vets_owner_id_idx on public.vets (owner_id);
