-- Campañas de donación (módulo 2)

create table public.campaigns (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  goal numeric not null default 0,
  current numeric not null default 0,
  donors integer not null default 0,
  days_left integer,
  organization text,
  status text not null default 'normal',
  updates integer not null default 0,
  creator_id uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create index campaigns_creator_id_idx on public.campaigns (creator_id);
