-- Create veterinaria table for Kany vets module
create table if not exists public.veterinaria (
  id bigint generated by default as identity primary key,
  title text not null,
  latitude double precision,
  longitude double precision,
  located_in text,
  category_name text,
  search_string text,
  address text,
  city text,
  phone text,
  website text,
  total_score numeric,
  url text,
  image_url text,
  description text,
  opening_hours_0_day text,
  opening_hours_0_hours text,
  opening_hours_1_day text,
  opening_hours_1_hours text,
  opening_hours_2_day text,
  opening_hours_2_hours text,
  opening_hours_3_day text,
  opening_hours_3_hours text,
  opening_hours_4_day text,
  opening_hours_4_hours text,
  opening_hours_5_day text,
  opening_hours_5_hours text,
  opening_hours_6_day text,
  opening_hours_6_hours text,
  source_file text,
  place_id text,
  hours_summary text,
  created_at timestamptz not null default now()
);

create unique index if not exists veterinaria_place_id_uidx
  on public.veterinaria (place_id)
  where place_id is not null;

create index if not exists veterinaria_city_idx on public.veterinaria (city);
create index if not exists veterinaria_category_idx on public.veterinaria (category_name);
create index if not exists veterinaria_search_string_idx on public.veterinaria (search_string);

alter table public.veterinaria enable row level security;

drop policy if exists "Public read veterinaria" on public.veterinaria;
create policy "Public read veterinaria"
  on public.veterinaria
  for select
  to anon, authenticated
  using (true);
