-- Chat privado entre usuarios alrededor de una publicacion de mascota perdida

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  lost_pet_id bigint not null references public.lost_pets (id) on delete cascade,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  participant_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_no_self_chat check (owner_id <> participant_id),
  constraint conversations_unique_lost_pet_participant unique (lost_pet_id, owner_id, participant_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 1000),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists conversations_owner_id_idx on public.conversations (owner_id);
create index if not exists conversations_participant_id_idx on public.conversations (participant_id);
create index if not exists conversations_lost_pet_id_idx on public.conversations (lost_pet_id);
create index if not exists messages_conversation_created_idx on public.messages (conversation_id, created_at);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;

create policy "Users can read own conversations"
  on public.conversations for select
  to authenticated
  using (owner_id = auth.uid() or participant_id = auth.uid());

create policy "Users can create conversations from lost pet reports"
  on public.conversations for insert
  to authenticated
  with check (
    participant_id = auth.uid()
    and owner_id <> auth.uid()
    and exists (
      select 1
      from public.lost_pets
      where lost_pets.id = lost_pet_id
        and lost_pets.reported_by = owner_id
    )
  );

create policy "Users can update own conversations"
  on public.conversations for update
  to authenticated
  using (owner_id = auth.uid() or participant_id = auth.uid())
  with check (owner_id = auth.uid() or participant_id = auth.uid());

create policy "Users can read messages from own conversations"
  on public.messages for select
  to authenticated
  using (
    exists (
      select 1
      from public.conversations
      where conversations.id = messages.conversation_id
        and (conversations.owner_id = auth.uid() or conversations.participant_id = auth.uid())
    )
  );

create policy "Users can send messages in own conversations"
  on public.messages for insert
  to authenticated
  with check (
    sender_id = auth.uid()
    and exists (
      select 1
      from public.conversations
      where conversations.id = messages.conversation_id
        and (conversations.owner_id = auth.uid() or conversations.participant_id = auth.uid())
    )
  );

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
  when undefined_object then
    create publication supabase_realtime for table public.messages;
end $$;
